name: Publish Container to GHCR

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Extract and build image from docker-compose.yml
      - name: Build and push Docker image
        run: |
          # Extract the image name and service from the docker-compose file
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:latest"
          
          # Build the service defined in docker-compose.yml
          docker compose build
          
          # Tag the image for GHCR
          docker compose images --quiet | xargs -I {} docker tag {} "$IMAGE_NAME"
          
          # Push the image to GHCR
          docker push "$IMAGE_NAME"